### ISSUE TITLE
How to change port?

### ISSUE THREAD

**Issue by Ruriko** [geraldwuhoo/omgur#2]
I can't use port 8080 cause I already have a different script running on that so how do I change the port?

**Comment by DUOLabs333** [comment]
try `export PORT=`

**Comment by DUOLabs333** [comment]
Seems like you can't -- you have to modify `main.go` to add it.

**Comment by geraldwuhoo** [comment]
As mentioned, not yet implemented. You can always run it with Docker and remap the hostPort:containerPort mapping to run it on a different port on your host.

**Comment by DUOLabs333** [comment]
#5 would add this.
