### ISSUE TITLE
Loading mp4s are slower than other requests

### ISSUE THREAD

**Issue by DUOLabs333** [geraldwuhoo/omgur#4]
As a continuation of #3, loading `http://localhost:8080/dkGFq4G.mp4` is slower than loading `http://localhost:8080/dkGFq4G.png` etc. This may be because it's a video, instead of a gif or image.

**Comment by geraldwuhoo** [comment]
Not sure there's much I can do about this. Videos are much larger than images and the program will have to spend more time downloading them to serve them. This is also the reason there is support for a Redis cache layer -- images/videos are pretty bandwidth heavy to it makes sense to store them in a local cache.
