### ISSUE TITLE
Prebuilt images

### ISSUE THREAD

**Issue by Mennaruuk** [geraldwuhoo/omgur#8]
Hey!!

I saw mentioned on GitLab that "Prebuilt images are also available at registry.geraldwu.com/gerald/omgur:latest and registry.gitlab.com/98wug/omgur:latest."

However, none of the links currently work.

Do you know where I can find the prebuilt images? They would be very helpful. Thanks!

P.S. Do you happen to know where I can find help on deploying to Replit or Glitch?

**Comment by geraldwuhoo** [comment]
Thanks for reporting this issue. I've changed my username on GitLab, and I forgot to update the GitLab container registry link in the README. This is fixed now.

My self-hosted GitLab appears to still be working on my side.

```
λ › docker pull registry.geraldwu.com/gerald/omgur:latest
latest: Pulling from gerald/omgur
540db60ca938: Pull complete
779b9e89c778: Pull complete
8c150f62c74f: Pull complete
Digest: sha256:b743d38071e3724b9becc0ecea2b7bfb6bfa86ede59d07c3b0d8cdf4e048cca9
Status: Downloaded newer image for registry.geraldwu.com/gerald/omgur:latest
registry.geraldwu.com/gerald/omgur:latest
```

Would you be able to post the exact error you're getting?

I have no experience with either Replit or Glitch, so you're unfortunately on your own there.

**Comment by Mennaruuk** [comment]
Both links are now working. I think something was off on my end when typing in the first URL. Thanks for fixing the second one. Really appreciate your help!!
